config/routes.rb
Rails.application.routes.draw do
  resources :images

  devise_for :users, controllers: { :registrations => 'registrations'}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user

  mount_uploader :picture, PictureUploader
  validate :picture_size, :stored_images

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "size should be less than 5MB")
    end
  end

  def stored_images
    if Image.all.count >= 100
      errors.add(:picture, "Whoops, something went wrong, try contacting me at joaquinberon2000@gmail.com")
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  attr_accessor :card_number, :cvc, :card_expires_month, :card_expires_year
  belongs_to :user

  def self.month_options
    Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i+1]}
  end

  def self.year_options
    (Date.today.year..(Date.today.year+10)).to_a
  end

  def process_payment
    customer = Stripe::Customer.create(email: user.email, card: token)

    Stripe::Charge.create(customer: customer.id,
                          amount: 1000,
                          description: 'Premium',
                          currency: 'usd')
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_one :payment
  accepts_nested_attributes_for :payment
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = current_user.images.build(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to image_url(@image), notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:name, :picture)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)

    resource.class.transaction do
      resource.save
      yield resource if block_given?
      if resource.persisted?
        @payment = Payment.new({ token: params[:payment]["token"],
                                 user_id: resource.id })

        flash[:error] = "Please check registration errors" unless @payment.valid?

        begin
          @payment.process_payment
          @payment.save
        rescue => exception
          flash[:error] = exception.message
          resource.destroy
          puts 'Payment failed'
          render :new and return
        end

        if resource.active_for_authentication?
          set_flash_message! :notice, :signed_up
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end

      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:payment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/images/_form.html.erb
<%= form_for @image, :html => { multipart: true, :class => "form-horizontal image" } do |f| %>

  <% if @image.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @image.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group mb-4">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group mb-4">
      <%= f.label :picture, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', :class => 'form-control' %>
      </div>
      <%=f.error_span(:picture) %>
    </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                images_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>">
  <p>
    <strong>Name:</strong>
    <%= image.name %>
  </p>

  <p>
    <strong>Picture:</strong>
    <%= image.picture %>
  </p>

  <p>
    <strong>User:</strong>
    <%= image.user_id %>
  </p>

</div>

app/views/images/edit.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/index.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1>Discover</h1>
</div>
  <div class="d-flex flex-column align-items-center mb-5">
    <% @images.each do |image| %>
      <div class="card mt-5" style= "width: 20rem">
        <%= image_tag(image.picture.url, { class: "card-img-top", alt: "thumbnail" })  %>
        <div class="card-header text-center"><strong><%= link_to(User.find(image.user_id).email, "#", class: "text-dark") %></strong></div>
        <div class="card-body">
          <h5 class="card-title text-center"><%= image.name %></h5>
        </div>
        <div class="card-footer">

          <div class="d-flex justify-content-around">
              <%= link_to t('.show', :default => t("helpers.links.show")),
                image_path(image), :class => 'btn btn-primary btn-sm' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_image_path(image), :class => 'btn btn-success btn-sm' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        image_path(image),
                        :data => { "turbo-method": :delete, turbo_confirm:'Are you sure?' },
                        :class => 'btn btn-danger btn-sm' %>
          </div>
        </div>
        </div>
    <% end %>
  </div>

  </div>
</div>

app/views/images/new.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/show.html.erb
<div class="container mb-5">
  <%- model_class = Image -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  </div>

  <dl class="dl-horizontal">
    <dt><%= model_class.human_attribute_name(:name) %>:</dt>
    <dd><strong><%= @image.name %></strong></dd>
    <dt></dt>
    <dd class="d-flex justify-content-center"><%= image_tag(@image.picture.url, class: "img-fluid") if @image.picture? %></dd>
    <dt>Uploaded by  <%= model_class.human_attribute_name(:user_id) %>:</dt>
    <dd><strong><%= User.find(@image.user_id).email %></strong></dd>
  </dl>

  <%= link_to t('.back', :default => t("helpers.links.back")),
                images_path, :class => 'btn btn-secondary'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_image_path(@image), :class => 'btn btn-secondary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                image_path(@image),
                :data => { "turbo-method": :delete, turbo_confirm:'Are you sure?' },
                :class => 'btn btn-danger' %>
</div>

app/views/layouts/_flash.html.erb
<% if !flash.keys.empty? %>
    <div class="alert alert-<%= flash[:alert] ? "warning" : "success" %> alert-dismissible fade show mt-3" role="alert">
        <% flash.each do |key, msg| %>
            <strong><%= msg %></strong>
        <% end %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="card-footer text-center bg-dark text-light" id="footer">
  <p class="m-0">Made by: <%= link_to "Joaquin Berrios", "https://joaquinb2000.github.io/Portfolio-site/", class: "text-info",target: :blank%> (2022)</p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-dark mb-3 px-5">
  <div class="container-fluid">
    <%= link_to "Photo App", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Discover", images_path, class:"nav-link active" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Upload Image", new_image_path, class: "nav-link"%>
        </li>
        <% end %>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0 align-items-center">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to("#", class: "nav-link") do %>
          <i class="bi bi-person-fill"></i>
          <%=current_user.email%>
          <% end%>
        </li>
        <li class="nav-item">
          <%= link_to("Logout", destroy_user_session_path, data: { turbo_method: :delete  }, class: "nav-link") %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to("Log in", new_user_session_path, class: "nav-link" )%>
        </li>
        <li class="nav-item">
          <%= link_to(new_user_registration_path, class: "nav-link" ) do%>
            <button class = "btn btn-primary">Sign up</button>
          <%end%>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <div class="container main mb-5">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
      <%= render "layouts/footer"%>
  </body>
</html>

app/views/welcome/_pricing_plan.html.erb
<div class="card card_pricing">
    <div class="card-body ">
        <div class="row">
        <h2 class="card-title"><%= title %></h2>

        </div>
        <ul class="mt-3">
            <% features.each do |feature|%>
                <li class="mb-2">
                    <p><%= feature %></p>
                </li>
            <%end%>
        </ul>
    </div>
        <div class="card-footer bg-dark text-light flex-column d-flex justify-content-center">
            <h3 class="text-center"><strong>$ <%= price %></strong></h3>
            <%= link_to "Sign up", new_user_registration_path, class:"btn btn-lg btn-primary"%>
        </div>
</div>

app/views/welcome/index.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Welcome to Photo App</h1>
        <p class="col-md-8 fs-4">Sign up, find out and use all of our functionalities!</p>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg"%>
    </div>
</div>

<% features = ["Unlimited Image Upload", "Unlimited image uploads", "Responsive design"]%>

<div class="row justify-content-around mb-5">
    <div class="col-5">
        <%= render partial: "pricing_plan", locals:
                                            {
                                                title: "Premium Plan",
                                                features: features,
                                                price: 10
                                            }
        %>
    </div>
    <div class="col-5">
        <%= render partial: "pricing_plan", locals:
                                            {
                                                title: "Amaze Plan",
                                                features: features.push("Unlimited Projects"),
                                                price: 20
                                            }
        %>
    </div>
</div>